spring:
  application:
    name: auth-service
server:
  port: 8189

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8762/eureka
    enabled: true

keycloak:
  auth-server-url: http://localhost:8180
  realm: spring-2026
  resource: backend
  credentials:
    secret: Pa6kdqdOFMo0pDsC4ddRQ3xRIIlXufVL
  management:
    endpoints:
      web:
        exposure:
          include: health, info
    endpoint:
      health:
        show-details: always