input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

output {
  if [app_name] {
      elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        # Logstash sẽ tạo index theo định dạng: order-service-logs-2024.05.20
        index => "%{app_name}-logs-%{+YYYY.MM.dd}"
      }
  } else {
    # Trường hợp log không có app_name (log hệ thống khác)
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "unknown-service-logs-%{+YYYY.MM.dd}"
    }
  }

  # Hiển thị ra console của docker để kiểm tra
  stdout { codec => rubydebug }
}